### ISSUE TITLE
LOC

### ISSUE THREAD

**Issue by deonlot** [walkjivefly/LOC-Extension#1]
Cannot install - get the following:

(com.sun.star.uno.RuntimeException) { { Message = "<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\\\tmp\\\\LOC_5476', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice 5\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice 5\\program\\pythonloader.py\", line 103, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\Deon\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu5340187u2.tmp_\\LOC.oxt\\loc.py\", line 38, in <module>\X000a    fh = logging.FileHandler(logfile, mode='a', encoding=None, delay=False)\X000a  File \"C:\\Program Files\\LibreOffice 5\\program\\python-core-3.5.0\\lib\\logging\\__init__.py\", line 1014, in __init__\X000a    StreamHandler.__init__(self, self._open())\X000a  File \"C:\\Program Files\\LibreOffice 5\\program\\python-core-3.5.0\\lib\\logging\\__init__.py\", line 1043, in _open\X000a    return open(self.baseFilename, self.mode, encoding=self.encoding)\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by walkjivefly** [comment]
Hi, sorry you've had a problem and thanks for reporting it rather than just giving it a thumbs-down on the extensions site. 
It looks like the problem is with the log file which the extension tries to create when it runs. Can you create a c:\tmp directory and try to install again. I don't have access to a windows machine right now to check if this will work. (As a matter of course I create a tmp directory for work files on any machine I use and hadn't considered what will happen when it's not there.) If that doesn't work I'll push a new version of the extension without logging enabled.

On linux when an extension installation fails LibreOffice can quickly get in a nasty mess because it doesn't do a good job of removing the partially installed extension. Hopefully that's not the case on Windows...

**Comment by qrsotuv** [comment]
Different guy buy tried adding the "c:\tmp" and didn't work. 

Also it does appears that windows keeps the extension in their when it fails.

**Comment by walkjivefly** [comment]
Thanks for the update and sorry the suggestion didn't work. I'll rebuild the extension later today with no logging and push the new version here and on the LO Extensions site.

**Comment by walkjivefly** [comment]
I have made a new [release](https://github.com/walkjivefly/LOC-Extension/releases/tag/v0.2.2) which I think will work around the installation problem on Windows. Please try it and let me know.

I don't currently have access to a Windows environment to test it on.

**Comment by walkjivefly** [comment]
I gather from the comments in Issue #2 that the new Windows release fixes the installation problem. Would either of @deonlot or @qrsotuv care to confirm that?

**Comment by walkjivefly** [comment]
Windows users are **STRONGLY** advised to make a Windows system snapshot before installing or upgrading ANY LibreOffice extension and to only use v[0.2.2](https://github.com/walkjivefly/LOC-Extension/tree/v0.2.2) LOC-Extension until further notice.
