### ISSUE TITLE
Compatibility with new CMC API key

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [walkjivefly/LOC-Extension#7]
"The Public API will be migrating to the new, more powerful Professional API on December 4th, 2018. Please update your application to use the free tier of the Professional API before then. "

If it's not compatible (due to added personal authentication key), will this ext. be upgraded as well?

I'm moving from google sheet to LOC. Wonder if I should do it now or later after I see that CMC is upgrading its API key. Thanks.

**Comment by walkjivefly** [comment]
@GreatBigWhiteWorld That's a very good question. I'll have to look into it. I don't have a LibreOffice development environment at present so if it requires code changes that is going to be a problem.

**Comment by walkjivefly** [comment]
As things stand, the ccxt("coinmarketcap",...) data source in LOC-Extension will stop working with the CMC API change.

This is unfortunate because with the "Public" API it is/was possible to pull ALL tickers from CMC in a single call, and cache the results, making it very efficient to use. Basically just one API call for all the ccxt("coinmarketcap",...) calls in a sheet. 

In the new "Professional" API this won't be possible, regardless of level the user has (paid for). It will require a call per currency or a reworking of the logic to batch all the required currencies into a single API call and "manual" caching if desired. At one call per currency you might as well ask for the price from your favourite exchange because it will be more current. This is only really an insurmountable problem if a coin is not on an exchange supported by the embedded version of ccxt. The embedded ccxt in LOC-Extension is very old and missing about 40 exchanges from the current version. 

I don't have the time or inclination to adapt the extension to use the new CMC API, nor embed the current ccxt. Unless someone else wants to step in, this will probably not be fixed and will be a permanent restriction going forwards.

**Comment by bobbyong** [comment]
Hi do you want to consider porting over to CoinGecko's free API? The format should be relatively easy to make the update: https://www.coingecko.com/api
